version: '3.9'

networks:
  web:
    external: 'true'

services:
  mind:
    container_name: mind
    image: 'mrcas/mind:latest'
    volumes:
      - './docker-volumes/mind/data:/app/db'
    env_file: .env
    expose:
     - 80
     - 443
    labels:
      # Traefik
      traefik.enable: 'true'
      traefik.frontend.rule: "Host:${MIND_HOST}"
      traefik.port: '8080'
      # Caddy
      caddy: ${MIND_HOST}
      caddy.reverse_proxy: "{{ upstreams 8080 }}"
    networks:
     - web
